version: '3'

networks:
  loki:
    driver: bridge

services:
  web-site:
    image: kadeguilherme/gerador-log:latest
    ports:
      - 3000:3000
    volumes:
      - ./logs:/logs
    environment:
      LOG_FILE: /logs/app.log
  
  loki:
    image: grafana/loki:2.5.0
    command: 
      - -config.file=/etc/loki/local-config.yaml
      - -print-config-stderr=true
    networks:
      - loki
    
  promtail:
    image: grafana/promtail:2.5.0
    command: -config.file=/etc/promtail/config.yaml
    depends_on:
      - loki
      - web-site
    networks:
      - loki
    ports:
      - 9080:9080
    volumes: 
      - ./logs:/logs
      - ./config.yaml:/etc/promtail/config.yaml